---
title: "Assignment 2"
format: html
---

## Objectives

This assignment provides you a chance to practice your skills manipulating geometries and building custom functions for iteration. It also asks you to think a bit about why these choices matter, not just computationally, but with in the context of your analysis. By the end of the assignment, you should be able to:

1. Align raster and vector data to a common CRS and explain why the choice of CRS is important.

2. Alter raster and vector geometries to explore and explain the Modifiable Areal Unit Problem (MAUP).

3. Create new variables (fields) with raster and vector data by using spatial measures.

4. Build introductory maps using `ggplot` to visualize your data

5. Describe the Atomic and Ecological Fallacy and identify where they might occur in your own research.

## Introducing the Data

In our Google Drive folder, you will find three datasets. The first is a shapefile of Idaho hospital locations taken from the Open Street Maps database (accessed via the `osmdata` package). The second is a shapefile from the [CDC Places dataset](https://www.cdc.gov/places/measure-definitions/index.html) depicting the modeled score for a variety of health indicators. You can access these by running our download function (you'll need to use `source` to do this when you load your packages) for [this link](https://drive.google.com/drive/folders/1tCbftdEbYZrr8beht-vTOUQdTx9u4sCJ). The last is a tabular dataset for a set of Idaho demographics downloaded from the `tidycensus`package. The data includes household income, total population, population breakdown by race, and a demographic dissimilarity score based on the `mutual_local` function in the [segregation package](https://cran.r-project.org/web/packages/segregation/vignettes/segregation.html).

## Overarching Question

Hospitals provide important services to a wide range of community members. That said, they aren't placed in the world at random. Your task in this assignment is to combine geoprocessing with visualization to see if you can identify key elements that correlate with the location of hospitals and think about what that might mean for the folks with and without access to those hospitals.

## Task 1: Getting Your Geometries Sorted

In order to do this analysis, you'll need to line up all of your spatial data and convert your tabular information to spatial data. 

1. Read your data into `R` (loading the appropriate data, packages, and functions) and check the geometries.

2. Use the [`tigris` package](https://github.com/walkerke/tigris) to download the shapefiles for Idaho's boundaries (state, county, tract, and block groups).

3. Use a spatial join to combine connect your cdc data to the tract shapefile and a tabular join to connect your demographic data to the blockgroups

4. Use [this webpage](https://epsg.io/) to find an appropriate projected CRS for Idaho and make sure all of your data are in that projection.

5. **Reflection:** Why do we want the data to have a common CRS? What characteristics did you look for when you were choosing your CRS? How might your choice affect the interpretation of the map?

6. **Bonus:** Make 3 maps depicting hospital location, a variable of your choosing, and the Idaho boundary using different projections. 

## Task 2: Creating New Data With Spatial Operations
For this section, you'll need to use spatial measures and predicates to calculate new variables.

1. Calculate the average distance between each block group and the nearest hospital. Use `ggplot` to explore the correlation between census demographics and distance to hospitals.

2. Do the same thing but comparing tract-level distances and 3 health indicators from the CDC data.

3. Write a function that is generic enough to take 2 vector datasets and calculate an average distance for each polygon in the first dataset.

4. Aggregate the demographic and health data to the county level. Then, create a new variable that contains the count of the number of hospitals in each county. Plot the correlation between your variables and the count of hospitals.

5. **Reflection**: How might the different spatial resolutions of your data affect the correlations you plotted? If there were differences in the correlations you plotted, what do you think is driving those differences?

## Task 3: Creating Rasters And Exploring the MAUP

Hospitals tend to serve communities outside of their specific location which means that the boundaries imposed by our data aren't as meaningful as we might like. We can overcome some of that by creating continuous fields (i.e., rasters) depicting the data throughout space. We can also explore how much things change if we make different assumptions about the "service area" of the hospital.

1. Generate rasters of total population density, median income, prevalence of individuals with CHD, and prevalence of Asthma (4 rasters total). Choose a resolution that makes sense to you given the question and your data.

2. Imagine that you have 3 hypotheses about the service area of a hospital. Use `map` and a `unary transformer` to generate these service are polygons and extract the raster data. Use ggplot to plot the correlations between your variables at each of your different service area sizes.

3. Use `aggregate` and `focal` to modify your rasters and coarsen them by a factor of 3. Recreate the plots from step 2 using the aggregated data.

4. Create a distance from hospital raster and estimate the correlation between the values in the distance raster and the values in your other 4 rasters.

5. **Reflection**: What did you imagine the biggest drivers of hospital location would be? Did your plots confirm this? How did changing the resolution of the data or the area over which you aggregated alter your conclusions?

## Task 4: Thinking about your work

In 200-400 words, describe the ecological fallacy and how it might manifest in your work. What are the risks associated with the ecological fallacy in your work and how might you identify and/or mitigate them.









